FROM wordpress:latest

# Custom PHP configurations
RUN echo "upload_max_filesize = 1024M" >> /usr/local/etc/php/conf.d/uploads.ini
RUN echo "post_max_size = 1024M" >> /usr/local/etc/php/conf.d/uploads.ini