name: Release WordPress Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Zip File
      run: zip -r cache-everything-${GITHUB_REF_NAME}.zip plugin/ -x "*.git*" -x "node_modules/*"

    - name: List files
      run: ls -l

    - name: Define GITHUB_REF_NAME
      run: echo "GITHUB_REF_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: "Description of the release"

    - name: Set asset path and name
      run: |
        echo "ASSET_PATH=./cache-everything-${GITHUB_REF_NAME}.zip" >> $GITHUB_ENV
        echo "ASSET_NAME=cache-everything-${GITHUB_REF_NAME}.zip" >> $GITHUB_ENV
      env:
        GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ASSET_PATH }}
        asset_name: ${{ env.ASSET_NAME }}
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
